import styles from '@/component/layouts/layout.module.css';
import Head from 'next/head';
import Header from '@/component/layouts/header';
import Content from '@/component/layouts/content';
import SideBar from '@/component/sideBar';
import Footer from '@/component/layouts/footer';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { Inter } from 'next/font/google';
import Breadcrumbs from '../props/breadcrumbs';
import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';
export default function Layout({ title, children }) {
  const router = useRouter();
  let nowPage = router.asPath;
  let pageTitle;
  if (!title) {
    nowPage.split('/').length == 2
      ? (pageTitle = nowPage.split('/')[1].toUpperCase() + '- Page')
      : (pageTitle = nowPage.split('/')[2].toUpperCase() + '- Page');
  } else {
    pageTitle = title + '- Post';
  }

  //footer  內容高度不超過100vh時botoom:0 否則 bottom 貼視窗底下
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-1.ico" />
      </Head>
      <div className={styles.body}>
        <Header />
        <div className={styles.container}>
          <Breadcrumbs nowPage={nowPage} />
          <br />
          {children}
          <Fab className={styles.fabContainer} color="primary" aria-label="add">
            <AddIcon />
          </Fab>
        </div>{' '}
        {/* 子组件位置 */}
        <Footer />
      </div>
    </>
  );
}
